### PR TITLE
Include farm_name in agent's data if specified

### PR DESCRIPTION
**Pull request by guidow**

### CODE REVIEW

**Comment by opalmer** [comment]
Code looks ok, config needs to be updated though to include the new value.

**Comment by guidow** [comment]
Hm, how do I include this so it defaults to ```None```?

**Comment by opalmer** [comment]
Update `pyfarm/agent/etc/agent.yml` with something like this would do it:

```yaml
# Including a comment above the value would be nice too so an administrator
# does not have to go looking elsewhere.
farm_name: null
```

**Comment by opalmer** [comment]
Looks good, thanks for the update.  Merging.

**Pull request merged**
