### PR TITLE
Improve Agent.post_shutdown_to_master tests.

### PR DESCRIPTION
**Pull request by opalmer**
This PR was created to simplify some of the tests for Agent.post_shutdown_to_master.  Mostly it removes many of the mocks and adds some additional output to post_shutdown_to_master that we can use when testing.  This also improves on a few tests that we inconsistently passing while working on #303.

### CODE REVIEW

**Comment by opalmer** [comment]
@guidow, PTAL

**Comment by opalmer** [comment]
@guidow, any comments on this one?

**Comment by opalmer** [comment]
@guidow, any comments or can I merge this?

**Comment by guidow** [comment]
Sorry for the long delay. This looks okay to me.

**Pull request merged**
