### PR TITLE
Remove CPU/RAM Update Methods

### PR DESCRIPTION
**Pull request by opalmer**
As discussed in #218 and #219 this change removes the code which POSTs CPU and RAM values to the master.  This code is currently unused and is being removed in favor os the reannouce functionality.

### CODE REVIEW

**Comment by opalmer** [comment]
@guidow, PTAL

**Comment by opalmer** [comment]
@guidow, you get a chance to have a look at this?

**Comment by guidow** [comment]
I'm going to have to keep an eye on whether or not automatic updates to free_ram still work, but other than that, this looks okay.

**Comment by opalmer** [comment]
Thanks.  That's actually something I'm also concerned about and my initial guess is it might be an issue on hosts which don't have a lot of work running through them.  That said, this should clean things up and if it turns out to not be enough we can always schedule more frequent updates or include free_ram in other POST requests.

**Pull request merged**
