### PR TITLE
[WIP] Update JobType Cache and Assignment Endpoint to use inlineCallbacks

### PR DESCRIPTION
**Pull request by opalmer**
This PR reworks the internal cache for jobtypes.  The main goals of this PR are to:

* Convert to `inlineCallbacks`
* Improve caching behavior, especially between cached and uncached modes.
* Fix a few subtle bugs in the jobtype cache.
* Update the assignment endpoint to use the new  `inlineCallbacks` to match the new cache implementation

### CODE REVIEW

**Comment by opalmer** [comment]
@guidow, PTAL.  It's going to need some additional testing but I think this is ready for a review.

**Comment by guidow** [comment]
This branch will fail to load a jobtype with the following error:

    2015-04-07 14:40:24 DEBUG    - HTTPChannel,4,127.0.0.1 - "127.0.0.1" - - [07/Apr/2015:12:40:23 +0000] "POST /api/v1/assign HTTP/1.1" 202 50 "-" "PyFarm/1.0 (master)"
    2015-04-07 14:40:24 INFO     - pf.agent.http.assign - Accepted assignment e62aab4b-6c40-46f3-916a-f267687b0100: {u'job': {u'ram_max': None, u'title': u'Massive test 36', u'ram': 32, u'batch': 5, u'cpus': 1, u'environ': {}, u'user': u'guido', u'id': 36, u'data': {u'output': u'/tmp/stift_####.exr', u'scene_file': u'/home/guido/stift_aniex43_finish.blend'}, u'by': 1.0, u'ram_warning': None}, u'tasks': [{u'frame': 141.0, u'attempt': 2, u'id': 17641}, {u'frame': 142.0, u'attempt': 2, u'id': 17642}, {u'frame': 143.0, u'attempt': 2, u'id': 17643}, {u'frame': 144.0, u'attempt': 2, u'id': 17644}, {u'frame': 145.0, u'attempt': 2, u'id': 17645}], 'id': UUID('e62aab4b-6c40-46f3-916a-f267687b0100'), u'jobtype': {u'version': 10, u'name': u'Render With Blender'}}
    2015-04-07 14:40:24 INFO     - pf.jobtypes.core - Downloading http://127.0.0.1:5000/api/v1/jobtypes/Render With Blender/versions/10
    2015-04-07 14:40:24 DEBUG    - HTTPChannel,4,127.0.0.1 - Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x7f8cf75ddbd8>
    2015-04-07 14:40:24 ERROR    - pf.agent.http.client - GET http://127.0.0.1:5000/api/v1/jobtypes/Render With Blender/versions/10 has failed (uid: e698d333ee50):
    Traceback (most recent call last):                                                                                                                                                    
    Failure: twisted.web._newclient.ResponseFailed: [<twisted.python.failure.Failure <class 'twisted.web._newclient.ParseError'>>]                                                        

    2015-04-07 14:40:24 ERROR    - pf.jobtypes.core - Error while attempting to download 'http://127.0.0.1:5000/api/v1/jobtypes/Render With Blender/versions/10': [<twisted.python.failure.Failure <class 'twisted.web._newclient.ParseError'>>]                                                                                                                                
    2015-04-07 14:40:24 ERROR    - pf.agent.http.assign - Loading jobtype for assignment e62aab4b-6c40-46f3-916a-f267687b0100 failed, removing.
    2015-04-07 14:40:24 DEBUG    - pf.agent.http.assign - Got traceback
    2015-04-07 14:40:24 ERROR    - pf.agent.http.assign - Traceback (most recent call last):
    Failure: twisted.web._newclient.ResponseFailed: [<twisted.python.failure.Failure <class 'twisted.web._newclient.ParseError'>>]                                                        

    2015-04-07 14:40:24 DEBUG    - pf.agent.http.assign - Marking tasks in assignment as failed

Meanwhile on the master, I see this error message:

    2015-04-07 14:40:24 ERROR    - werkzeug        - 127.0.0.1 - - [07/Apr/2015 14:40:24] code 400, message Bad request syntax ('GET /api/v1/jobtypes/Render With Blender/versions/10 HTTP/1.1')

Would you mind explaining a bit more how this PR actually improves things? What I am seeing here is mostly redoing things that were already working and had most of their bugs ironed out already in a slightly different way that introduces new bugs...

**Comment by opalmer** [comment]
The main improvements that this PR is trying to make are a few things:

* Finer grained threading.  Before we were sending larger portions of code into treads when we really only needed to thread a couple of operations to eliminate potential points where the reactor could be blocked.
* Locks around portions of the code where we're interacting with the cache.  Before it was possible to update the cache and before we 'check' it again.
* Fixed cached/uncached behaviors.  "Disabled caching" didn't actually exist before because it wouldn't always retrieve the updated job type and it would still cache the module on every call which is not a behavior you'd expect when something is uncached.  
* A few other minor improvements mainly focused on reducing the number of different methods we need to implement JobType.load (which makes it easier to understand) and improving testability. 
* Conversion to inlineCallbacks.  This improves on the readability quite a bit and also simplifies the flow some.  It's also less prone to swallowing errors in unexpected ways. 

Functionally speaking there are not a great deal of differences here that should break anything, most of this was focused on improving what we already have and eliminating bugs we would have eventually hit.  But obviously there's something I've missed here (sorry, again).  It probably has to do with the way the tests were written and/or how the request is made to the master so I'll looking into this deeper from that perspective before another review.

**Comment by opalmer** [comment]
@guidow, I know this has some merge conflicts and some things that need to be updated.  If I can get this in working order again would you mind having another look?

**Comment by opalmer** [comment]
I'm going to go ahead and abandon this:

* It's a rather large PR, it should be broken down more.
* Let's get better test coverage first.
* There's a lot of little changes which conflict with this and because it's new code it will be easier to introduce subtle bugs.

**Pull request closed without merging**
