### PR TITLE
Fix shutdown when requested via API

### PR DESCRIPTION
**Pull request by guidow**

### CODE REVIEW

**Comment by opalmer** [comment]
Looks like the tests are failing because the reactor is being stopped mid-test.  You'll probably need to update some of the API tests to mock out `reactor.stop()` then test to make sure it is in fact called.

**Comment by opalmer** [comment]
Couple suggestions:

* You will probably need to mock out `reactor.stop()` in some of the api tests in order for this to work
* Use `stopping = config["agent"].sigint_handler()` instead of calling `stop()` directly.  That will handle stopping the agent, the reactor, return the proper exit code and remove the control file.

**Comment by guidow** [comment]
> * Use `stopping = config["agent"].sigint_handler()` instead of calling `stop()` directly.  That will handle stopping the agent, the reactor, return the proper exit code and remove the control file.  If the behavior needs to vary slightly I'd rather we make a small update to `sigint_handler()` to handle it.

I need the control file to remain put in some of these cases, so this isn't really an option.

**Comment by opalmer** [comment]
> I need the control file to remain put in some of these cases, so this isn't really an option.

Makes sense, mocking `reactor.mock()` would do fine then.  Looks like that's fixed so I'll go ahead and merge this.

**Pull request merged**
